### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by JonTJ** [szmnmichalowski/ZF2-NoCaptcha#5]
Hi there,

Im getting the following error:

Parse error: syntax error, unexpected '[' in ...szmnmichalowski/zf2-nocaptcha/src/NoCaptcha/Captcha/ReCaptcha.php on line 78

The offending line is:

`$options = $options === null ? [] : $options;`

In your composer.json file you are requiring php >= 5.3.0 but this short hand syntax for arrays was only introduced in 5.4. Due to restraints i am still using 5.3.x for the time being and this is breaking my forms. May i suggest an update to the declaration of the constructor:

`public function __construct($options = array())`

as this would remove the need for the offending line. I have updated this in my vendor library but obviously if any updates are released this will get overwritten when i run composer update.

Also on an unrelated note, you have a typo in your readme; where you are showing examples of instantiating the main Recaptcha class you need to captialise Captcha:

`$captcha = new \NoCaptcha\Captcha\Re**C**aptcha($options);`

Many thanks!
Jon

**Comment by szmnmichalowski** [comment]
Hello Jon!

Thank you for using my module. It's good to see that some people find this piece of code helpful.
I just pushed changes according to information you have given me.

I hope, you will not find any more inconvenience :)

Regards
Szymon

**Comment by JonTJ** [comment]
Hey Szymon

No worries, thanks for writing it! And also thanks for the speedy response, will run an update on composer now.

Many thanks!
Jon
